### ISSUE TITLE
.default.send is not a function

### ISSUE THREAD

**Issue by Vardan-bg** [VKCOM/vk-bridge-mock#11]
Доброго времени суток!
Этот код на версии 2.0.1:

```
import bridge from '@vkontakte/vk-bridge-mock';

bridge.send('VKWebAppGetUserInfo', {}).then(data => {
  console.log(data)
});
```

дает ошибку:
.default.send is not a function

На 2.0.0 все исправно работает

**Comment by mahnunchik** [comment]
`TypeError: _bridge__WEBPACK_IMPORTED_MODULE_44__.default.send is not a function` — аналогичная ошибка, версия `2.0.1`.

**Comment by danakt** [comment]
Исправлено в 2.0.2
